### ISSUE TITLE
Publish new versions of Octokit Libraries using @octokit/types

### ISSUE THREAD

**Issue by gr2m** [octokit/types.ts#3]
- [x] octokit/endpoint.js#107
- [x] octokit/request.js#92
- [x] octokit/graphql.js#63
- [x] octokit/auth-token.js#10
- [x] octokit/auth-app.js#23
- [x] octokit/auth-basic.js#12 
- [x] octokit/auth-oauth-app.js#19
- [x] octokit/core.js#16
